### ISSUE TITLE
module Any = { module Old = Mock.AnyOld; }

### ISSUE THREAD

**Issue by idkjs** [hoichi/hoichi.io#23]
Greetings @hoichi!

I was studying your blog! Thanks for taking the time to teach.

I am trying to follow along with the [ttdd post](https://hoichi.io/blog/ttdd/) and ran into: 

```ocaml
module Any = { module Old = Mock.AnyOld; }

let postWithDate =
  dateStr => Post.{
    meta: {
      ...Any.Old.meta,
      date: Js.Date.fromString(dateStr),
    },
    title: "",
    content: Markup.Markdown(""),
    excerpt: Markup.Markdown(""),
    source: Any.Old.source,
  };

let postsArray = Belt.Array.map(_, postWithDate);
let addPosts = (c: Collection.t, posts) =>
  postsArray(posts)->Belt.Array.reduce(c, Collection.add);

```

Since I dont have a stash of old Mocks, can you share an example how you implemented that?

Thank you, again.

**Comment by hoichi** [comment]
Hey Alain!

Well, there are some real-life mocks here: https://github.com/hoichi/hoichi.io/tree/dd388251340f35b1138cd69556a972cf5dc03df6/src/__tests__/mocks

But after 2 years I'm not sure how they correspond to what happens in the post. I definitely think that puns on "any old mock" is a very bad joke, and doesn't improve clarity.

Otoh, I still think having mocks in ReScript/Reason (so the mocks have correct types) is still probably a good idea. Why bother with decoding/converting, when you keep your tests minimal and maintainable :)

**Comment by idkjs** [comment]
@hoichi, my brother. Thank you for taking the time to respond. You need not worry about the age of the files. I am extremely practiced at updating even the worst oldest reason code to learn something.

Thanks for hunting these down. I need to see that code run to see how it works.

Best always.
